[versions]
agp = "9.3.1"
kotlin = "2.4.10"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
miuix = "0.9.4-rc01"
okhttp = "4.12.0"
jsoup = "1.17.2"
hutool = "5.8.27"
gson = "2.10.1"
semver = "2.0.0"
compileSdk = "37"
minSdk = "29"

# Compose 相关版本
composeUi = "1.8.1"
composeMaterial = "1.8.1"
composeMaterial3 = "1.4.0"
activityCompose = "1.12.4"
composeRuntime = "1.8.1"
composeFoundation = "1.8.1"
composeRuntimeLivedata = "1.8.1"
kotlinxCoroutinesCore = "1.7.2"
kotlinxCoroutinesAndroid = "1.7.2"
kotlinxCoroutinesCompose = "1.7.2"

# Lifecycle 相关版本
lifecycle = "2.10.0"

# Parcelable 列表支持
parcelablelist = "2.0.1"

# Room 数据库相关版本
room = "2.8.2"
keepassJava2 = "2.2.4"
biometric = "1.1.0"
ktlint = "14.2.0"
autofill = "1.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
androidx-autofill = { group = "androidx.autofill", name = "autofill", version.ref = "autofill" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
miuix-android = { module = "top.yukonga.miuix.kmp:miuix-ui-android", version.ref = "miuix" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
hutool-core = { group = "cn.hutool", name = "hutool-core", version.ref = "hutool" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
semver = { group = "io.github.z4kn4fein", name = "semver", version.ref = "semver" }

# Compose 相关库
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeUi" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeUi" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUi" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "composeRuntime" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "composeFoundation" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "composeRuntimeLivedata" }
miuix-icons = { module = "top.yukonga.miuix.kmp:miuix-icons-android", version.ref = "miuix" }
miuix-preference = { module = "top.yukonga.miuix.kmp:miuix-preference", version.ref = "miuix" }

# Navigation 相关库
miuix-nav = { module = "top.yukonga.miuix.kmp:miuix-nav-android", version.ref = "miuix" }

# Parcelable 列表支持
dev-rikka-parcelablelist = { module = "dev.rikka.rikkax.parcelablelist:parcelablelist", version.ref = "parcelablelist" }
# Room 数据库相关库
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
keepassjava2-kdbx = { group = "org.linguafranca.pwdb", name = "KeePassJava2-kdbx", version.ref = "keepassJava2" }
keepassjava2-dom = { group = "org.linguafranca.pwdb", name = "KeePassJava2-dom", version.ref = "keepassJava2" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-compose = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-compose", version.ref = "kotlinxCoroutinesCompose" }

[bundles]
kotlinx-coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-android"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.10" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

