apply plugin: 'com.android.library'

android {
    namespace 'com.kunzisoft.keepass.icon'
    compileSdkVersion 37

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 35
    }

    compileOptions {
        targetCompatibility JavaVersion.VERSION_17
        sourceCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    api project(path: ':icon-pack:classic')
    api project(path: ':icon-pack:material')
}
